export const URL={
   login:"/login",
   forgot_password: "/forgot_password",
   password_setup: "/password_setup",
   sent_successfull:"/sent_successfull",
   password_SetUp_Successfull: "/password_setup_sucessfull",
   dashboard: "/",
   admission: "/admission_list",
   add_admission: "/add_admission",
   view_addmission_details: "/view_admission_details",
   view_admission_details1: "/view_admission_details1",
   view_addmission_details2: "/view_admission_details2",
   teamList: "/team_list",
   add_team: "/add_team",
   view_team: "/view_team",
   mainSource: "/main_source",
   add_mainSource: "/add_mainSource",
   subSource: "/sub_source",
   courseList: "/course_list",
   branchList: "/branch_list",
   add_branch: "/add_branch",
   accountList: "/account_list",
   add_account: "/add_account",
   whatsapp: "/whatsapp_list",
   add_whatsapp: "/add_whatsapp_message",
   mail: "/mail",
   add_mail: "/add_mail",
   profile: "/profile",
   add_sub_source: "/add_sub_source",
   add_course : "/add_course",
   updateProfile: "update-profile",
   error: "/*",
}